apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-additional-singleuser-profiles
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      profiles:
      - name: Additional Profile
        env:
          - name: ds-dev-pod
            value: "My Workspace"
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 2